import MyProfilePic from "./components/MyProfilePic";
import NavBar from "./components/NavBar";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Braulio's Blog",
  description: "Generated by Braulio Estrada",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"dark:bg-slate-800"}>
        <NavBar></NavBar>
        <MyProfilePic />
        {children}
      </body>
    </html>
  );
}
